import { TokenType } from "@/Tokens/Token";

export enum PredefinedTokenValues {
    abstract = "abstract",
    any = "any",
    as = "as",
    assert = "assert",
    async = "async",
    await = "await",
    boolean = "boolean",
    break = "break",
    byte = "byte",
    case = "case",
    catch = "catch",
    char = "char",
    class = "class",
    const = "const",
    constructor = "constructor",
    continue = "continue",
    declare = "declare",
    default = "default",
    delete = "delete",
    do = "do",
    double = "double",
    else = "else",
    enum = "enum",
    export = "export",
    extends = "extends",
    false = "false",
    finally = "finally",
    float = "float",
    for = "for",
    from = "from",
    function = "function",
    if = "if",
    implements = "implements",
    import = "import",
    in = "in",
    instanceof = "instanceof",
    int = "int",
    interface = "interface",
    is = "is",
    let = "let",
    long = "long",
    module = "module",
    namespace = "namespace",
    new = "new",
    null = "null",
    number = "number",
    object = "object",
    of = "of",
    package = "package",
    private = "private",
    public = "public",
    require = "require",
    return = "return",
    short = "short",
    static = "static",
    string = "string",
    super = "super",
    switch = "switch",
    then = "then",
    this = "this",
    throw = "throw",
    true = "true",
    try = "try",
    type = "type",
    typeof = "typeof",
    undefined = "undefined",
    var = "var",
    void = "void",
    while = "while",
    with = "with",
    yield = "yield",
}

export const tokenTypeByPredefinedTokenValue: Record<
    PredefinedTokenValues,
    TokenType
> = {
    [PredefinedTokenValues.abstract]: TokenType.keyword,
    [PredefinedTokenValues.any]: TokenType.type,
    [PredefinedTokenValues.as]: TokenType.keyword,
    [PredefinedTokenValues.assert]: TokenType.keyword,
    [PredefinedTokenValues.async]: TokenType.keyword,
    [PredefinedTokenValues.await]: TokenType.keyword,
    [PredefinedTokenValues.boolean]: TokenType.type,
    [PredefinedTokenValues.break]: TokenType.keyword,
    [PredefinedTokenValues.byte]: TokenType.type,
    [PredefinedTokenValues.case]: TokenType.keyword,
    [PredefinedTokenValues.catch]: TokenType.keyword,
    [PredefinedTokenValues.char]: TokenType.type,
    [PredefinedTokenValues.class]: TokenType.keyword,
    [PredefinedTokenValues.const]: TokenType.keyword,
    [PredefinedTokenValues.constructor]: TokenType.keyword,
    [PredefinedTokenValues.continue]: TokenType.keyword,
    [PredefinedTokenValues.declare]: TokenType.keyword,
    [PredefinedTokenValues.default]: TokenType.keyword,
    [PredefinedTokenValues.delete]: TokenType.keyword,
    [PredefinedTokenValues.do]: TokenType.keyword,
    [PredefinedTokenValues.double]: TokenType.type,
    [PredefinedTokenValues.else]: TokenType.keyword,
    [PredefinedTokenValues.enum]: TokenType.keyword,
    [PredefinedTokenValues.export]: TokenType.keyword,
    [PredefinedTokenValues.extends]: TokenType.keyword,
    [PredefinedTokenValues.false]: TokenType.constant,
    [PredefinedTokenValues.finally]: TokenType.keyword,
    [PredefinedTokenValues.float]: TokenType.type,
    [PredefinedTokenValues.for]: TokenType.keyword,
    [PredefinedTokenValues.from]: TokenType.keyword,
    [PredefinedTokenValues.function]: TokenType.keyword,
    [PredefinedTokenValues.if]: TokenType.keyword,
    [PredefinedTokenValues.implements]: TokenType.keyword,
    [PredefinedTokenValues.import]: TokenType.keyword,
    [PredefinedTokenValues.in]: TokenType.keyword,
    [PredefinedTokenValues.int]: TokenType.type,
    [PredefinedTokenValues.instanceof]: TokenType.keyword,
    [PredefinedTokenValues.interface]: TokenType.keyword,
    [PredefinedTokenValues.is]: TokenType.keyword,
    [PredefinedTokenValues.let]: TokenType.keyword,
    [PredefinedTokenValues.long]: TokenType.type,
    [PredefinedTokenValues.module]: TokenType.keyword,
    [PredefinedTokenValues.namespace]: TokenType.keyword,
    [PredefinedTokenValues.new]: TokenType.keyword,
    [PredefinedTokenValues.null]: TokenType.constant,
    [PredefinedTokenValues.number]: TokenType.type,
    [PredefinedTokenValues.object]: TokenType.type,
    [PredefinedTokenValues.of]: TokenType.keyword,
    [PredefinedTokenValues.package]: TokenType.keyword,
    [PredefinedTokenValues.private]: TokenType.keyword,
    [PredefinedTokenValues.public]: TokenType.keyword,
    [PredefinedTokenValues.require]: TokenType.keyword,
    [PredefinedTokenValues.return]: TokenType.keyword,
    [PredefinedTokenValues.short]: TokenType.type,
    [PredefinedTokenValues.static]: TokenType.keyword,
    [PredefinedTokenValues.string]: TokenType.type,
    [PredefinedTokenValues.super]: TokenType.keyword,
    [PredefinedTokenValues.switch]: TokenType.keyword,
    [PredefinedTokenValues.then]: TokenType.keyword,
    [PredefinedTokenValues.this]: TokenType.keyword,
    [PredefinedTokenValues.throw]: TokenType.keyword,
    [PredefinedTokenValues.true]: TokenType.constant,
    [PredefinedTokenValues.try]: TokenType.keyword,
    [PredefinedTokenValues.type]: TokenType.keyword,
    [PredefinedTokenValues.typeof]: TokenType.keyword,
    [PredefinedTokenValues.undefined]: TokenType.constant,
    [PredefinedTokenValues.var]: TokenType.keyword,
    [PredefinedTokenValues.void]: TokenType.keyword,
    [PredefinedTokenValues.while]: TokenType.keyword,
    [PredefinedTokenValues.with]: TokenType.keyword,
    [PredefinedTokenValues.yield]: TokenType.keyword,
};
