export enum TextmateScope {
    blockComment = "comment.block",
    character = "constant.character",
    comment = "comment.line.character",
    constant = "constant.language",
    function = "entity.name.function",
    keyword = "keyword.control",
    number = "constant.numeric",
    operator = "keyword.operator",
    parameter = "variable.parameter",
    punctuation = "punctuation.definition",
    separator = "punctuation.separator",
    string = "string.quoted",
    terminator = "punctuation.terminator",
    type = "storage.type",
}
